using Business.Dtos;
using Data.Entities;
using Data.Repositories;
using Domain.Enums;

namespace Business.Services;

// Central gate for private event visibility: hosts, co-hosts, and accepted attendees only.
// Generated by AI
public interface IEventAccessService
{
    bool HasViewAccess(EventEntity eventEntity, string userId);
    Task<EventResult> VerifyViewAccessAsync(string userId, string eventId);
    Task<EventResult> RedeemShareTokenAsync(string userId, string eventId, string token);
    Task<EventResult<string>> GetOrCreateShareLinkAsync(string userId, string eventId);
    Task<EventResult> RevokeShareLinkAsync(string userId, string eventId);
}

public class EventAccessService( IEventRepository eventRepository, IEventShareLinkRepository shareLinkRepository, IEventAttendanceRepository attendanceRepository) : IEventAccessService
{
    private readonly IEventRepository _eventRepository = eventRepository;
    private readonly IEventShareLinkRepository _shareLinkRepository = shareLinkRepository;
    private readonly IEventAttendanceRepository _attendanceRepository = attendanceRepository;

    // **************************************************************************************************************************
    // Host/co-host or any attendance row that is not hidden from the user's lists.
    public bool HasViewAccess(EventEntity eventEntity, string userId)
    {
        return HasListMembership(eventEntity, userId);
    }

    // **************************************************************************************************************************
    // Checks if the user has list membership.
    internal static bool HasListMembership(EventEntity eventEntity, string userId)
    {
        if (eventEntity.Roles.Any(r =>
                r.UserId == userId &&
                !r.HiddenFromList &&
                (r.Role == EventRoleType.Owner || r.Role == EventRoleType.CoOwner)))
            return true;

        return eventEntity.Attendances.Any(a =>
            a.UserId == userId && !a.HiddenFromList);
    }

    // **************************************************************************************************************************
    // Verifies if the user has view access to an event.
    public async Task<EventResult> VerifyViewAccessAsync(string userId, string eventId)
    {
        var response = await _eventRepository.GetEntityAsync(
            e => e.Id == eventId,
            includes: [x => x.Roles, x => x.Attendances]);

        if (!response.Succeeded || response.Result == null)
            return new EventResult { Succeeded = false, StatusCode = 404, ErrorMessage = "Event not found." };

        if (!HasViewAccess(response.Result, userId))
            return new EventResult { Succeeded = false, StatusCode = 404, ErrorMessage = "Event not found." };

        return new EventResult { Succeeded = true, StatusCode = 200 };
    }

    // **************************************************************************************************************************
    // Validates a share token and ensures a pending attendance row so the visitor can open the event
    // without accepting RSVP; JoinEventAsync sets Accepted when they click Join.
    public async Task<EventResult> RedeemShareTokenAsync(string userId, string eventId, string token)
    {
        if (string.IsNullOrWhiteSpace(token))
            return new EventResult { Succeeded = false, StatusCode = 400, ErrorMessage = "Share token is required." };

        var linkResponse = await _shareLinkRepository.GetByEventAndTokenAsync(eventId, token.Trim());
        if (!linkResponse.Succeeded || linkResponse.Result == null)
            return new EventResult { Succeeded = false, StatusCode = 404, ErrorMessage = "Event not found." };

        if (linkResponse.Result.IsRevoked)
            return new EventResult { Succeeded = false, StatusCode = 404, ErrorMessage = "Event not found." };

        var eventResponse = await _eventRepository.GetEntityAsync(
            e => e.Id == eventId,
            includes: [x => x.Roles, x => x.Attendances]);

        if (!eventResponse.Succeeded || eventResponse.Result == null)
            return new EventResult { Succeeded = false, StatusCode = 404, ErrorMessage = "Event not found." };

        if (HasViewAccess(eventResponse.Result, userId))
            return new EventResult { Succeeded = true, StatusCode = 200 };

        var attendanceResponse = await _attendanceRepository.GetEntityAsync(
            a => a.UserId == userId && a.EventId == eventId);

        if (attendanceResponse.Succeeded && attendanceResponse.Result != null)
        {
            var attendance = attendanceResponse.Result;
            if (attendance.Status != AttendanceStatus.Accepted)
                attendance.Status = AttendanceStatus.Pending;

            attendance.HiddenFromList = false;
            attendance.GuestCount = Math.Max(1, attendance.GuestCount);

            var updateResult = await _attendanceRepository.UpdateAsync(attendance);
            return updateResult.Succeeded
                ? new EventResult { Succeeded = true, StatusCode = 200 }
                : new EventResult { Succeeded = false, StatusCode = updateResult.StatusCode, ErrorMessage = updateResult.ErrorMessage };
        }

        var addResult = await _attendanceRepository.AddAsync(new EventAttendanceEntity
        {
            EventId = eventId,
            UserId = userId,
            Status = AttendanceStatus.Pending,
            HiddenFromList = false,
            GuestCount = 1,
        });

        return addResult.Succeeded
            ? new EventResult { Succeeded = true, StatusCode = 201 }
            : new EventResult { Succeeded = false, StatusCode = addResult.StatusCode, ErrorMessage = addResult.ErrorMessage };
    }

    // **************************************************************************************************************************
    // Gets or creates a share link for an event.
    public async Task<EventResult<string>> GetOrCreateShareLinkAsync(string userId, string eventId)
    {
        var hostError = await VerifyHostAccessAsync(userId, eventId);
        if (hostError != null)
            return new EventResult<string> { Succeeded = false, StatusCode = hostError.StatusCode, ErrorMessage = hostError.ErrorMessage };

        var existing = await _shareLinkRepository.GetActiveByEventIdAsync(eventId);
        if (existing.Succeeded && existing.Result != null)
            return new EventResult<string> { Succeeded = true, StatusCode = 200, Result = existing.Result.Token };

        var addResult = await _shareLinkRepository.AddAsync(new EventShareLinkEntity
        {
            EventId = eventId,
            CreatedByUserId = userId,
            Token = Guid.NewGuid().ToString("N"),
            IsRevoked = false,
            CreatedAt = DateTime.UtcNow
        });

        if (!addResult.Succeeded)
            return new EventResult<string> { Succeeded = false, StatusCode = addResult.StatusCode, ErrorMessage = addResult.ErrorMessage };

        var created = await _shareLinkRepository.GetActiveByEventIdAsync(eventId);
        return created.Succeeded && created.Result != null
            ? new EventResult<string> { Succeeded = true, StatusCode = 201, Result = created.Result.Token }
            : new EventResult<string> { Succeeded = false, StatusCode = 500, ErrorMessage = "Could not create share link." };
    }

    // **************************************************************************************************************************
    // Revokes a share link for an event.
    public async Task<EventResult> RevokeShareLinkAsync(string userId, string eventId)
    {
        var hostError = await VerifyHostAccessAsync(userId, eventId);
        if (hostError != null)
            return hostError;

        var linkResponse = await _shareLinkRepository.GetActiveByEventIdAsync(eventId);
        if (!linkResponse.Succeeded || linkResponse.Result == null)
            return new EventResult { Succeeded = true, StatusCode = 200 };

        var link = linkResponse.Result;
        link.IsRevoked = true;

        var updateResult = await _shareLinkRepository.UpdateAsync(link);
        return updateResult.Succeeded
            ? new EventResult { Succeeded = true, StatusCode = 200 }
            : new EventResult { Succeeded = false, StatusCode = updateResult.StatusCode, ErrorMessage = updateResult.ErrorMessage };
    }

    // **************************************************************************************************************************
    // Verifies if the user has host access to an event.
    private async Task<EventResult?> VerifyHostAccessAsync(string userId, string eventId)
    {
        var response = await _eventRepository.GetEntityAsync(
            e => e.Id == eventId,
            includes: [x => x.Roles]);

        if (!response.Succeeded || response.Result == null)
            return new EventResult { Succeeded = false, StatusCode = 404, ErrorMessage = "Event not found." };

        var isHost = response.Result.Roles.Any(r =>
            r.UserId == userId &&
            (r.Role == EventRoleType.Owner || r.Role == EventRoleType.CoOwner));

        if (!isHost)
            return new EventResult { Succeeded = false, StatusCode = 403, ErrorMessage = "You do not have permission to manage share links for this event." };

        return null;
    }
}
