using System.ComponentModel.DataAnnotations;
using Domain.Enums;
using Domain.Models;
using Presentation.Helpers;

namespace Presentation.Models;

public class AddEventViewModel
{
    /// <summary>Set when editing an existing event via <c>/events/create?edit={id}</c>.</summary>
    public string? EventId { get; set; }

    public bool IsEdit => !string.IsNullOrWhiteSpace(EventId);

    [Required(ErrorMessage = "Please enter an event title.")]
    [StringLength(500)]
    public string Title { get; set; } = null!;

    [StringLength(160)]
    public string? Slug { get; set; }

    [StringLength(2048)]
    [Url]
    public string? CoverImageUrl { get; set; }

    [StringLength(8000)]
    public string? Description { get; set; }

    public string? Date { get; set; }

    public string? Time { get; set; }

    public DateTimeOffset StartAt { get; set; }

    public DateTimeOffset? EndAt { get; set; }

    /// <summary>Bound from form <c>name="location"</c>.</summary>
    public string? Location { get; set; }

    [Required]
    [StringLength(100)]
    public string Timezone { get; set; } = "Europe/Stockholm";

    [StringLength(300)]
    public string? LocationName { get; set; }

    [StringLength(500)]
    public string? LocationStreet { get; set; }

    [StringLength(32)]
    public string? LocationPostcode { get; set; }

    [StringLength(120)]
    public string? LocationCity { get; set; }

    [StringLength(100)]
    public string? LocationCountry { get; set; }

    public JoinMode JoinMode { get; set; } = JoinMode.Open;

    public bool JoinButton { get; set; }

    public EventStatus Status { get; set; } = EventStatus.Active;

    public bool ChatEnabled { get; set; }

    public bool? ItemsTasksEnabled { get; set; }

    public bool? AllowGuestBringItems { get; set; }

    public bool? AllowGuestTasks { get; set; }

    [StringLength(120)]
    public string? PaymentMethod { get; set; }

    [StringLength(120)]
    public string? PaymentNumber { get; set; }

    [StringLength(200)]
    public string? PaymentName { get; set; }

    [StringLength(32)]
    public string? PaymentAmount { get; set; }

    [StringLength(200)]
    public string? PaymentComment { get; set; }

    /// <summary>Serialized draft bring-items from the create-event modal (JSON array).</summary>
    /// Generated by AI.
    public string? DraftBringItemsJson { get; set; }

    /// <summary>Serialized draft guest tasks from the create-event modal (JSON array).</summary>
    /// Generated by AI.
    public string? DraftGuestTasksJson { get; set; }

    public AddEventFormData ToAddFormData() => new()
    {
        Title = Title,
        Slug = Slug,
        CoverImageUrl = CoverImageUrl,
        Description = Description,
        StartAt = StartAt,
        EndAt = EndAt,
        Timezone = Timezone,
        LocationName = LocationName,
        LocationStreet = LocationStreet,
        LocationPostcode = LocationPostcode,
        LocationCity = LocationCity,
        LocationCountry = LocationCountry,
        JoinMode = JoinMode,
        Status = Status,
        ChatEnabled = ChatEnabled,
        ItemsTasksEnabled = ItemsTasksEnabled,
        AllowGuestBringItems = AllowGuestBringItems,
        AllowGuestTasks = AllowGuestTasks,
        PaymentMethod = PaymentMethod,
        PaymentNumber = PaymentNumber,
        PaymentName = PaymentName,
        PaymentAmount = CreateEventFormHelper.ParsePaymentAmount(PaymentAmount),
        PaymentComment = PaymentComment,
    };

    public UpdateEventFormData ToUpdateFormData() => new()
    {
        Title = Title,
        Slug = Slug,
        CoverImageUrl = CoverImageUrl,
        Description = Description,
        StartAt = StartAt,
        EndAt = EndAt,
        Timezone = Timezone,
        LocationName = LocationName,
        LocationStreet = LocationStreet,
        LocationPostcode = LocationPostcode,
        LocationCity = LocationCity,
        LocationCountry = LocationCountry,
        JoinMode = JoinMode,
        Status = Status,
        ChatEnabled = ChatEnabled,
        ItemsTasksEnabled = ItemsTasksEnabled,
        AllowGuestBringItems = AllowGuestBringItems,
        AllowGuestTasks = AllowGuestTasks,
        PaymentMethod = PaymentMethod,
        PaymentNumber = PaymentNumber,
        PaymentName = PaymentName,
        PaymentAmount = CreateEventFormHelper.ParsePaymentAmount(PaymentAmount),
        PaymentComment = PaymentComment,
    };
}
