namespace Domain.Enums;
//Generated by AI
public enum EventVisibility
{
    Private,
    Public
}

public enum JoinMode
{
    Open,
    InviteOnly,
    Disabled
}

public enum EventStatus
{
    Active,
    Cancelled,
    Deleted
}

public enum AttendanceStatus
{
    Accepted,
    Declined,
    Maybe,
    Pending
}

public enum EventRoleType
{
    Owner,
    CoOwner
}

public enum SignupMode
{
    Available,
    Disabled,
    Hidden
}

public enum AssigneeType
{
    User,
    Everyone,
    OpenSlot
}

public enum AssignmentStatus
{
    Assigned,
    SignedUp,
    Completed,
    Removed
}
